version: '3.8'
services:
  next_app:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app_network

  node_backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:3000"
    environment:
      - MONGO_URI=${MONGO_URI}
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
